name: Node.js CI/CD

on:
    path: ["scheduler-app/**", ".github/workflows/cicd_aws_oidc_scheduler_app_pipeline.yml"]
  push:
    branches:
      - main
        
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
      # Set the working directory globally for all 'run' steps in this job
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build --if-present
      
      - name: Upload artifacts #options to upload build/test artifacts for later jobs
        uses: actions/upload-artifact@v7
        with:
          name: node-app-artifacts
          path: .


  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: . # Specify the build context (e.g., the directory containing the Dockerfile)
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/scheduler-app:v2.1
            ${{ secrets.DOCKER_USERNAME }}/scheduler-app:${{ github.sha }}


  deploy-AWS-eks:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: <Role ARN you created in step 2>
          aws-region: <AWS Region you want to use>
          role-session-name: MySessionName
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity

